version: "3"
services:
  app:
    build: .
    environment:
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ANECDOTES_TABLE=${ANECDOTES_TABLE}
      - DATES_TABLE=${DATES_TABLE}
      - DIALOGS_TABLE=${DIALOGS_TABLE}
      - DATASET_TABLE=${DATASET_TABLE}
      - GPT3_ENGINE=${GPT3_ENGINE}
      - MEDICINES_TABLE=${MEDICINES_TABLE}
      - SERVICE_STATUS=${SERVICE_STATUS}
      - STATUS_TABLE=${STATUS_TABLE}
      - USERS_TABLE=${USERS_TABLE}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
    volumes:
      - ./app/:/app
      - ./data/:/data
    working_dir: /app
    container_name: app
    command: tail -F anything