version: "3"
services:
  app:
    build:
      context: .
      target: app
    environment:
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ANECDOTES_TABLE=${ANECDOTES_TABLE}
      - DATES_TABLE=${DATES_TABLE}
      - DIALOGS_TABLE=${DIALOGS_TABLE}
      - DATASET_TABLE=${DATASET_TABLE}
      - GPT3_ENGINE=${GPT3_ENGINE}
      - MEDICINES_TABLE=${MEDICINES_TABLE}
      - SERVICE_STATUS=${SERVICE_STATUS}
      - STATUS_TABLE=${STATUS_TABLE}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
    volumes:
      - ./app/:/app
      - ./data/:/data
      - ./poc/:/poc
      - ./credentials/:/credentials
    working_dir: /app
    container_name: app
    command: tail -F anything
  model:
    build:
      context: .
      target: model
    volumes:
      - ./model:/home/jovyan/app
      - ./data:/home/jovyan/data
    ports:
      - 8830:8888
    container_name: model
