version: "3"
services:
  experiments:
    build: ./experiments
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes:
      - ./experiments/:/home/jovyan/
    ports:
      - 8820:8888
    container_name: experiments

  app:
    build: ./app
    environment:
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes:
      - ./app/:/app
      - ./logs/:/logs
      - ./database/:/database
    working_dir: /app
    container_name: app
    command: tail -F anything

  sqlite3:
    image: nouchka/sqlite3:latest
    stdin_open: true
    tty: true
    volumes:
      - ./database/:/database/