version: "3"
services:
  app:
    build: .
    environment:
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes:
      - ./app/:/app
    working_dir: /app
    container_name: app
    command: tail -F anything